In [1]:
#Importing libraries
import pandas as pd
from pathlib import Path

## Setting up DataFrames

In [2]:
#Setting path to CSV files
aug_data = "Resources/JC-202207-citibike-tripdata.csv"
sep_data = "Resources/JC-202208-citibike-tripdata.csv"
oct_data = "Resources/JC-202209-citibike-tripdata.csv"

In [3]:
#Creating DataFrames for each resource
aug_df = pd.read_csv(aug_data)
sep_df = pd.read_csv(sep_data)
oct_df = pd.read_csv(oct_data)

In [4]:
#Display DataFrame
print(f"Length: {len(aug_df)}")
aug_df.head()

Length: 108502

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,89CDCE3224502904,classic_bike,2022-07-21 18:19:45,2022-07-21 18:28:21,Marshall St & 2 St,HB408,8 St & Washington St,HB603,40.740802,-74.042521,40.745984,-74.028199,member
1,3E6E50F51BD4CBD9,electric_bike,2022-07-21 17:50:57,2022-07-21 17:59:17,Marshall St & 2 St,HB408,11 St & Washington St,HB502,40.740802,-74.042521,40.749985,-74.027150,casual
2,8A9058FAA9115562,electric_bike,2022-07-23 11:51:55,2022-07-23 11:59:16,Marshall St & 2 St,HB408,Oakland Ave,JC022,40.740802,-74.042521,40.737604,-74.052478,member
3,C566A187663748AE,classic_bike,2022-07-30 20:34:40,2022-07-30 20:48:40,Marshall St & 2 St,HB408,Bloomfield St & 15 St,HB203,40.740802,-74.042521,40.754530,-74.026580,member
4,7E754D57276BE57E,classic_bike,2022-07-14 18:42:34,2022-07-14 18:49:45,Marshall St & 2 St,HB408,Clinton St & 7 St,HB303,40.740802,-74.042521,40.745420,-74.033320,casual

In [5]:
#Display DataFrame
print(f"Length: {len(sep_df)}")
sep_df.head()

Length: 115231

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,D68047AAA9A72501,classic_bike,2022-08-12 18:14:45,2022-08-12 18:21:23,Columbus Drive,JC014,Hamilton Park,JC009,40.718355,-74.038914,40.727596,-74.044247,member
1,E5B82A9F588A7650,classic_bike,2022-08-19 01:04:39,2022-08-19 01:14:10,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
2,13D19CCBCC9D7B76,classic_bike,2022-08-19 18:13:45,2022-08-19 19:32:47,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
3,AA0DBFF220DA98F6,classic_bike,2022-08-21 13:43:05,2022-08-21 13:53:13,Columbus Drive,JC014,Montgomery St,JC099,40.718355,-74.038914,40.719420,-74.050990,member
4,8F11D340492FCD32,electric_bike,2022-08-04 22:02:12,2022-08-04 22:21:31,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Pershing Field,JC024,40.736982,-74.027781,40.742677,-74.051789,member

In [6]:
#Display DataFrame
print(f"Length: {len(oct_df)}")
oct_df.head()

Length: 104247

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4999883C92EACCB0,classic_bike,2022-09-01 21:05:47,2022-09-01 21:08:07,Jersey & 3rd,JC074,Brunswick St,JC023,40.723332,-74.045953,40.724176,-74.050656,member
1,CC87E6815E075F6F,classic_bike,2022-09-10 18:09:26,2022-09-10 18:11:48,Jersey & 3rd,JC074,Brunswick St,JC023,40.723225,-74.045679,40.724176,-74.050656,member
2,B54E7FDDF4C251E6,classic_bike,2022-09-26 21:46:24,2022-09-26 21:56:06,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723275,-74.045694,40.723332,-74.045953,member
3,A19A3DC77A98F6C2,classic_bike,2022-09-08 20:11:41,2022-09-08 22:01:29,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723230,-74.045731,40.723332,-74.045953,member
4,3530E340A0B0E93F,classic_bike,2022-09-08 17:05:38,2022-09-08 17:10:26,Leonard Gordon Park,JC080,Riverview Park,JC057,40.745789,-74.057112,40.744319,-74.043991,member

In [7]:
#Concat aug and sep DataFrames
combined_df = pd.concat([aug_df, sep_df])
combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,89CDCE3224502904,classic_bike,2022-07-21 18:19:45,2022-07-21 18:28:21,Marshall St & 2 St,HB408,8 St & Washington St,HB603,40.740802,-74.042521,40.745984,-74.028199,member
1,3E6E50F51BD4CBD9,electric_bike,2022-07-21 17:50:57,2022-07-21 17:59:17,Marshall St & 2 St,HB408,11 St & Washington St,HB502,40.740802,-74.042521,40.749985,-74.027150,casual
2,8A9058FAA9115562,electric_bike,2022-07-23 11:51:55,2022-07-23 11:59:16,Marshall St & 2 St,HB408,Oakland Ave,JC022,40.740802,-74.042521,40.737604,-74.052478,member
3,C566A187663748AE,classic_bike,2022-07-30 20:34:40,2022-07-30 20:48:40,Marshall St & 2 St,HB408,Bloomfield St & 15 St,HB203,40.740802,-74.042521,40.754530,-74.026580,member
4,7E754D57276BE57E,classic_bike,2022-07-14 18:42:34,2022-07-14 18:49:45,Marshall St & 2 St,HB408,Clinton St & 7 St,HB303,40.740802,-74.042521,40.745420,-74.033320,casual

In [8]:
#Concat final DataFrame to combined DataFrame
combined_df = pd.concat([combined_df, oct_df])
#Check len of combined dataframe
print(f"Length: {len(combined_df)}")
#Display Dataframe
combined_df.head()

Length: 327980

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,89CDCE3224502904,classic_bike,2022-07-21 18:19:45,2022-07-21 18:28:21,Marshall St & 2 St,HB408,8 St & Washington St,HB603,40.740802,-74.042521,40.745984,-74.028199,member
1,3E6E50F51BD4CBD9,electric_bike,2022-07-21 17:50:57,2022-07-21 17:59:17,Marshall St & 2 St,HB408,11 St & Washington St,HB502,40.740802,-74.042521,40.749985,-74.027150,casual
2,8A9058FAA9115562,electric_bike,2022-07-23 11:51:55,2022-07-23 11:59:16,Marshall St & 2 St,HB408,Oakland Ave,JC022,40.740802,-74.042521,40.737604,-74.052478,member
3,C566A187663748AE,classic_bike,2022-07-30 20:34:40,2022-07-30 20:48:40,Marshall St & 2 St,HB408,Bloomfield St & 15 St,HB203,40.740802,-74.042521,40.754530,-74.026580,member
4,7E754D57276BE57E,classic_bike,2022-07-14 18:42:34,2022-07-14 18:49:45,Marshall St & 2 St,HB408,Clinton St & 7 St,HB303,40.740802,-74.042521,40.745420,-74.033320,casual

## Correcting Lat/Lng variance

In [9]:
#Average Lat/Lng values by station name for start values
start_lat = combined_df.groupby(["start_station_name"])["start_lat"].mean()
start_lng = combined_df.groupby(["start_station_name"])["start_lng"].mean()

In [10]:
#Display data
start_lat

start_station_name
11 St & Washington St                40.749989
12 St & Sinatra Dr N                 40.750610
14 St Ferry - 14 St & Shipyard Ln    40.752931
4 St & Grand St                      40.742266
5 Corners Library                    40.734971
                                       ...
Van Vorst Park                       40.718481
Warren St                            40.721121
Washington St                        40.724291
Willow Ave & 12 St                   40.751882
York St & Marin Blvd                 40.716615
Name: start_lat, Length: 81, dtype: float64

In [11]:
#Update Dataframe with corrected Lat/Lng values for each start station name
for station in start_lat.index:
    combined_df.loc[combined_df["start_station_name"] == station, "start_lat"] = start_lat[station]
    combined_df.loc[combined_df["start_station_name"] == station, "start_lng"] = start_lng[station]
    
combined_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,89CDCE3224502904,classic_bike,2022-07-21 18:19:45,2022-07-21 18:28:21,Marshall St & 2 St,HB408,8 St & Washington St,HB603,40.740775,-74.042541,40.745984,-74.028199,member
1,3E6E50F51BD4CBD9,electric_bike,2022-07-21 17:50:57,2022-07-21 17:59:17,Marshall St & 2 St,HB408,11 St & Washington St,HB502,40.740775,-74.042541,40.749985,-74.027150,casual
2,8A9058FAA9115562,electric_bike,2022-07-23 11:51:55,2022-07-23 11:59:16,Marshall St & 2 St,HB408,Oakland Ave,JC022,40.740775,-74.042541,40.737604,-74.052478,member
3,C566A187663748AE,classic_bike,2022-07-30 20:34:40,2022-07-30 20:48:40,Marshall St & 2 St,HB408,Bloomfield St & 15 St,HB203,40.740775,-74.042541,40.754530,-74.026580,member
4,7E754D57276BE57E,classic_bike,2022-07-14 18:42:34,2022-07-14 18:49:45,Marshall St & 2 St,HB408,Clinton St & 7 St,HB303,40.740775,-74.042541,40.745420,-74.033320,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104242,914104109C27B9C8,electric_bike,2022-09-09 21:50:46,2022-09-09 22:02:44,Madison St & 1 St,HB402,Columbus Dr at Exchange Pl,JC106,40.738787,-74.039280,40.716870,-74.032810,casual
104243,BF8C9DCD3FE530E7,classic_bike,2022-09-18 17:52:19,2022-09-18 18:05:22,Monmouth and 6th,JC075,Bergen Ave & Stegman St,JC108,40.725672,-74.048799,40.706575,-74.086701,member
104244,F7DCB86572EC4732,electric_bike,2022-09-28 16:46:08,2022-09-28 16:50:46,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,member
104245,A552D06A517E37E4,classic_bike,2022-09-27 11:39:59,2022-09-27 11:43:58,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,member
104246,CDCAE5569A0464EF,classic_bike,2022-09-02 20:55:22,2022-09-02 21:01:41,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,casual

In [12]:
#Average Lat/Lng values by station name for end values
end_lat = combined_df.groupby(["end_station_name"])["end_lat"].mean()
end_lng = combined_df.groupby(["end_station_name"])["end_lng"].mean()

In [13]:
#Display Data
end_lat

end_station_name
1 Ave & E 30 St         40.741444
10 Ave & W 14 St        40.741982
10 Ave & W 28 St        40.750664
11 Ave & W 41 St        40.760301
11 Ave & W 59 St        40.771497
                          ...
West Thames St          40.708347
William St & Pine St    40.707179
Willow Ave & 12 St      40.751867
York St                 40.716490
York St & Marin Blvd    40.716615
Name: end_lat, Length: 221, dtype: float64

In [14]:
#Update Dataframe with corrected Lat/Lng values for each end station name
for station in end_lat.index:
    combined_df.loc[combined_df["end_station_name"] == station, "end_lat"] = end_lat[station]
    combined_df.loc[combined_df["end_station_name"] == station, "end_lng"] = end_lng[station]
    
combined_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,89CDCE3224502904,classic_bike,2022-07-21 18:19:45,2022-07-21 18:28:21,Marshall St & 2 St,HB408,8 St & Washington St,HB603,40.740775,-74.042541,40.745984,-74.028199,member
1,3E6E50F51BD4CBD9,electric_bike,2022-07-21 17:50:57,2022-07-21 17:59:17,Marshall St & 2 St,HB408,11 St & Washington St,HB502,40.740775,-74.042541,40.749985,-74.027150,casual
2,8A9058FAA9115562,electric_bike,2022-07-23 11:51:55,2022-07-23 11:59:16,Marshall St & 2 St,HB408,Oakland Ave,JC022,40.740775,-74.042541,40.737604,-74.052478,member
3,C566A187663748AE,classic_bike,2022-07-30 20:34:40,2022-07-30 20:48:40,Marshall St & 2 St,HB408,Bloomfield St & 15 St,HB203,40.740775,-74.042541,40.754530,-74.026580,member
4,7E754D57276BE57E,classic_bike,2022-07-14 18:42:34,2022-07-14 18:49:45,Marshall St & 2 St,HB408,Clinton St & 7 St,HB303,40.740775,-74.042541,40.745420,-74.033320,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104242,914104109C27B9C8,electric_bike,2022-09-09 21:50:46,2022-09-09 22:02:44,Madison St & 1 St,HB402,Columbus Dr at Exchange Pl,JC106,40.738787,-74.039280,40.716870,-74.032810,casual
104243,BF8C9DCD3FE530E7,classic_bike,2022-09-18 17:52:19,2022-09-18 18:05:22,Monmouth and 6th,JC075,Bergen Ave & Stegman St,JC108,40.725672,-74.048799,40.706575,-74.086701,member
104244,F7DCB86572EC4732,electric_bike,2022-09-28 16:46:08,2022-09-28 16:50:46,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,member
104245,A552D06A517E37E4,classic_bike,2022-09-27 11:39:59,2022-09-27 11:43:58,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,member
104246,CDCAE5569A0464EF,classic_bike,2022-09-02 20:55:22,2022-09-02 21:01:41,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742266,-74.035091,40.749943,-74.035865,casual

In [15]:
#Export cleaned DataFrame to CSV
combined_df.to_csv("Resources/CleanData.csv")